services:
  identity-mssql:
    container_name: identity-mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    # build:
    #   context: .
    #   dockerfile: mssql.dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - ./scripts:/var/opt/mssql/scripts
    # command: >
    #   /bin/bash -c "
    #     /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P P@ssw0rd -d master -C -i /var/opt/mssql/scripts/log.sql;"

  # identity-api:
  #   container_name: identity-api
  #   build:
  #     context: .
  #     dockerfile: api.dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on:
  #     - identity-mssql
